name: Testing Delete Package Versions

on:
    workflow_dispatch:        

permissions: 
    contents: read

jobs:
    delete-package-versions:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Delete Package Versions
              shell: bash
              run: |
                pip install -r requirements.txt                
                python main.py
              env:
                  PAT: ${{ secrets.PAT }}
                  PACKAGE_LIST : '["npm-proj"]'
                  PACKAGE_TYPE: npm
                  DELETE_VERSIONS_PATTERN: "0."
                  RETENTION_NUMBER: 3
