name: Testing Delete Package Versions

on:
    workflow_dispatch:

permissions: 
    contents: read

jobs:
    delete-package-versions:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Delete Package Versions
              shell: bash
              run: |
                pip install -r requirements.txt
                chmod +x delete_package_versions.py
                python delete_package_versions.py
              env:
                  PAT: ${{ secrets.PAT }}
